// Generated by scripts/board-islands.mjs — do not edit by hand.
// Atlas rectangle [uMin, vMin, uMax, vMax] of each investigation-board paper
// piece, plus the atlas directions of the paper's own right/down axes.
export interface BoardIsland {
  uv: [number, number, number, number];
  right: [number, number];
  down: [number, number];
}

export const boardIslands = {
  Plane058__0: { uv: [0.41938, 0.11418, 0.6691, 0.49253], right: [0, -1], down: [-1, 0] },
  Plane059__0: { uv: [0.88189, 0.29497, 0.93633, 0.36737], right: [-1, 0], down: [0, 1] },
  Plane060__0: { uv: [0.79514, 0.29588, 0.85049, 0.36795], right: [-1, 0], down: [0, 1] },
  Plane061__0: { uv: [0.84402, 0.57452, 0.89436, 0.64701], right: [0, -1], down: [-1, 0] },
  Plane062__0: { uv: [0.86902, 0.39533, 0.96242, 0.53024], right: [0, 1], down: [1, 0] },
  Plane063__0: { uv: [0.93599, 0.21803, 0.9774, 0.27762], right: [0, 1], down: [1, 0] },
  Plane064__0: { uv: [0.73992, 0.28126, 0.78086, 0.32382], right: [0, -1], down: [-1, 0] },
  Plane065__0: { uv: [0.73926, 0.2259, 0.77971, 0.26785], right: [0, -1], down: [-1, 0] },
  Plane066__0: { uv: [0.79575, 0.39234, 0.83705, 0.45259], right: [0, -1], down: [-1, 0] },
  Plane067__0: { uv: [0.72259, 0.56908, 0.77619, 0.64628], right: [0, -1], down: [-1, 0] },
  Plane068__0: { uv: [0.80541, 0.2293, 0.84597, 0.27155], right: [0, -1], down: [-1, 0] },
  Plane069__0: { uv: [0.7839, 0.57055, 0.83413, 0.64265], right: [0, -1], down: [-1, 0] },
  Plane070__0: { uv: [0.90272, 0.55448, 0.96776, 0.64785], right: [0, -1], down: [-1, 0] },
  Plane071__0: { uv: [0.79372, 0.47305, 0.84322, 0.54647], right: [0, -1], down: [-1, 0] },
  Plane072__0: { uv: [0.73082, 0.47425, 0.78051, 0.54605], right: [0, 1], down: [1, 0] },
  Plane073__0: { uv: [0.73526, 0.40773, 0.77605, 0.45035], right: [0, -1], down: [-1, 0] },
  Plane074__0: { uv: [0.87454, 0.23119, 0.91482, 0.27448], right: [0, -1], down: [-1, 0] },
  Plane075__0: { uv: [0.736, 0.34455, 0.77662, 0.38685], right: [0, -1], down: [-1, 0] },
} satisfies Record<string, BoardIsland>;

export type BoardPieceId = keyof typeof boardIslands;
