#!/usr/bin/env node
/**
 * Development-only: extracts each investigation-board paper piece's atlas
 * rectangle and paper orientation, and writes
 * src/experience/surfaces/boardIslands.ts for the CASE 404 board repaint.
 *
 * Orientation is found by least-squares fitting UV against the piece's
 * position on the board face (right = -z, up = +y), then snapping the
 * paper's right/down directions to the nearest atlas axis.
 *
 * Usage: node scripts/board-islands.mjs
 */
import { writeFileSync } from "node:fs";
import { NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";

const SRC = "public/models/case-404/environment/investigation-board.glb";
const OUT = "src/experience/surfaces/boardIslands.ts";

const io = new NodeIO().registerExtensions(ALL_EXTENSIONS);
const doc = await io.read(SRC);

function solve3(S, R) {
  const det = (M) =>
    M[0][0] * (M[1][1] * M[2][2] - M[1][2] * M[2][1]) -
    M[0][1] * (M[1][0] * M[2][2] - M[1][2] * M[2][0]) +
    M[0][2] * (M[1][0] * M[2][1] - M[1][1] * M[2][0]);
  const D = det(S);
  return [0, 1, 2].map((c) => det(S.map((row, i) => row.map((x, j) => (j === c ? R[i] : x)))) / D);
}

const snap = ([u, v]) => (Math.abs(u) > Math.abs(v) ? [Math.sign(u), 0] : [0, Math.sign(v)]);

const islands = {};
for (const node of doc.getRoot().listNodes()) {
  const mesh = node.getMesh();
  if (!mesh || !node.getName().startsWith("Plane")) continue;
  const prim = mesh.listPrimitives()[0];
  const pos = prim.getAttribute("POSITION");
  const uv = prim.getAttribute("TEXCOORD_0");
  const m = node.getWorldMatrix();
  const S = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0],
  ];
  const Ru = [0, 0, 0];
  const Rv = [0, 0, 0];
  let uMin = 1,
    vMin = 1,
    uMax = 0,
    vMax = 0;
  for (let i = 0; i < pos.getCount(); i++) {
    const [x, y, z] = pos.getElement(i, []);
    const right = -(m[2] * x + m[6] * y + m[10] * z + m[14]);
    const up = m[1] * x + m[5] * y + m[9] * z + m[13];
    const [u, v] = uv.getElement(i, []);
    const r = [right, up, 1];
    for (let a = 0; a < 3; a++) {
      Ru[a] += r[a] * u;
      Rv[a] += r[a] * v;
      for (let b = 0; b < 3; b++) S[a][b] += r[a] * r[b];
    }
    uMin = Math.min(uMin, u);
    vMin = Math.min(vMin, v);
    uMax = Math.max(uMax, u);
    vMax = Math.max(vMax, v);
  }
  const [au, bu] = solve3(S, Ru);
  const [av, bv] = solve3(S, Rv);
  const right = snap([au, av]);
  const down = snap([-bu, -bv]);
  // Runtime (three.js) node names drop the dots: Plane.058__0 -> Plane058__0.
  islands[node.getName().replace(/\./g, "")] = {
    uv: [uMin, vMin, uMax, vMax].map((n) => Number(n.toFixed(5))),
    right,
    down,
  };
}

const body = Object.entries(islands)
  .map(([k, v]) => `  ${k}: ${JSON.stringify(v).replace(/"(\w+)":/g, "$1: ")},`)
  .join("\n");
writeFileSync(
  OUT,
  `// Generated by scripts/board-islands.mjs — do not edit by hand.
// Atlas rectangle [uMin, vMin, uMax, vMax] of each investigation-board paper
// piece, plus the atlas directions of the paper's own right/down axes.
export interface BoardIsland {
  uv: [number, number, number, number];
  right: [number, number];
  down: [number, number];
}

export const boardIslands = {
${body}
} satisfies Record<string, BoardIsland>;

export type BoardPieceId = keyof typeof boardIslands;
`,
);
console.log(`wrote ${OUT} (${Object.keys(islands).length} pieces)`);
